config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'static_pages#home'
  get '/admin', to: redirect('/admin/posts')
  get '/posts', to: 'static_pages#posts'
  get '/:id' => 'static_pages#show', as: :public_show
  resources :categories, only: [:index, :show ]
  namespace :admin do

    resources :posts
    resources :categories
  end
  post '/tinymce_assets', to: 'tinymce_assets#create'

end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :posts
  extend FriendlyId
  friendly_id :name, use: [:slugged, :history]

end

app/models/image.rb
class Image < ActiveRecord::Base
  has_attached_file :attachment,
    :styles => {
      :medium => "300x300>",
      :thumb => "100x100>"
      },
    :default_url => "/images/:style/missing.png"
    
  validates_attachment_content_type :attachment, :content_type => /\Aimage\/.*\Z/





end

app/models/post.rb
class Post < ActiveRecord::Base
  paginates_per 10
  extend FriendlyId
  friendly_id :title, use: [:slugged, :history]

  belongs_to :category

  validates_presence_of :body, :title, :pub_date, :tags
  scope :featured,  -> { where(featured: true ).where("pub_date < ?", DateTime.now).limit(3).where(draft: false) }
  scope :sidebar,   -> { where(sidebar: true ).where("pub_date < ?", DateTime.now).limit(3).where(draft: false) }
  scope :published, -> { where('pub_date < ?', DateTime.now).where(draft: false) }
  scope :pending,   -> { where('pub_date > ?', DateTime.now).where(draft: false) }

  has_attached_file :main_image,
    :styles => {
      :medium => "355x288>",
      :thumb => "100x100>"
      },
    :default_url => "/images/:style/missing.png"

  validates_attachment_content_type :main_image, :content_type => /\Aimage\/.*\Z/


  def status
    if draft
      "Draft"
    elsif pub_date > DateTime.now
      "Awating Publish Date"
    else
      "Published"
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name
  has_many :visits
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < ApplicationController
skip_before_filter :track_action
  def show
    @category = Category.friendly.find params[:id]
  end


  def index
    @categories = Category.all
  end

  def edit
    @category = Category.friendly.find params[:id]
  end

  def new
    @category = Category.new
  end

  def update
    @category = Category.friendly.find params[:id]
    if @category.update_attributes category_params
      redirect_to admin_category_path(@category)
    else
      redirect_to :back, notice: "Sorry love, something went wrong."
    end
  end

  def create
    @category = Category.new category_params
    if @category.save
      redirect_to admin_category_path(@category)
    else
      redirect_to :back, notice: "Sorry love, Something went wrong."
    end
  end

  def destroy
    @category = Category.friendly.find params[:id]
  end

  private

  def category_params
    params[:category].permit(:name, :description)
  end
end

app/controllers/admin/posts_controller.rb
class Admin::PostsController < ApplicationController
  skip_before_filter :track_action
  layout 'application'
  before_action :authenticate_user!
  def index
    @posts = Post.order(:created_at).page params[:page]
  end

  def show
    @post = Post.friendly.find params[:id]
  end


  def update
    @post = Post.friendly.find params[:id]
    @post.update_attributes post_params
    if @post.save
      redirect_to [:admin, @post]
    else
      redirect_to :back, notice: @post.errors
    end
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to [:admin, @post]
    else
      redirect_to :back, notice: @post.errors
    end
  end


  def new
    @post = Post.new
    @categories = Category.all
  end


  def edit
    @post = Post.friendly.find params[:id]
    @categories = Category.all
  end

  def destroy
    @post = Post.friendly.find params[:id]
    if @post.delete
      redirect_to admin_posts_path
    else
      redirect_to :back, notice: "Something went wrong."
    end
  end

  private

  def post_params
    params[:post].permit(:title, :body, :tags, :pub_date, :main_image, :draft, :sidebar, :featured, :category_id)
  end

end

app/controllers/admin/tinymce_assets_controller.rb
class Admin::TinymceAssetsController < ApplicationController
  respond_to :json
  skip_before_filter :track_action

  def create
    image = Image.new attachment: image_params["file"].tempfile
    if image.save
      render json: {
            image: {
              url: image.attachment.url
            }
          }, content_type: "text/html"
    else
      render json: {errors: "Upload Failed" }, status: 500
    end
  end


  private

  def image_params
    params.permit(:file)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  after_filter :track_action

  protected

  def track_action
    ahoy.track "Processed #{controller_name}##{action_name}", request.filtered_parameters
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :find_sidebar

  layout 'public'
  def show
    @category = Category.friendly.find params[:id]
  end

  def index
    @categories = Category.all
  end


  private

  def find_sidebar
    @sidebar_posts  = Post.sidebar
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  layout 'application'
  before_action :authenticate_user!
  def index
    @posts = Post.order(:created_at).page params[:page]
  end

  def show
    @post = Post.friendly.find params[:id]
  end


  def update
    @post = Post.find params[:id]
    @post.update_attributes post_params
    if @post.save
      redirect_to @post
    else
      redirect_to new_post_path, notice: @post.errors
    end
  end

  def create
    @post = Post.new post_params
    if @post.save
      redirect_to @post
    else
      redirect_to new_post_path, notice: @post.errors
    end
  end


  def new
    @post = Post.new
  end


  def edit
    @post = Post.find params[:id]
  end

  private

  def post_params
    params[:post].permit(:title, :body, :tags, :pub_date, :main_image, :draft, :sidebar, :featured)
  end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  before_action :find_sidebar

  layout 'public'

  def home
    @featured_posts = Post.featured
    @sidebar_posts  = Post.sidebar
  end

  def show
    @post = Post.friendly.find params[:id]
    ahoy.track "Viewed book", title: @post.title
  end

  def posts
    @posts = Post.all
  end

  private

  def find_sidebar
    @sidebar_posts  = Post.sidebar
  end
end

app/controllers/tinymce_assets_controller.rb
class TinymceAssetsController < ApplicationController
  respond_to :json

  def create
    image = Image.new attachment: image_params["file"].tempfile
    if image.save
      render json: {
            image: {
              url: image.attachment.url
            }
          }, content_type: "text/html"
    else
      render json: {errors: "Upload Failed" }, status: 500
    end
  end


  private

  def image_params
    params.permit(:file)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def title(page_title)
    content_for(:title, page_title.to_s)
    return content_tag(:h1, page_title)
  end
end

app/views/admin/categories/edit.slim
.small-12.medium-8.columns.small-centered.medium-centered
  br
  br
  h1 Edit Category
  = form_for([:admin, @category]) do |f|
    .row
      .large-6.columns.small-12
        =f.label :name
        =f.text_field :name

    =f.label :description
    =f.text_area :description, rows: "8", class: "tinymce"

    =f.submit "Update Category"
br
br

javascript:
  $("document:ready", function() {
    $(".tinymce").tinymce({
      theme: "modern",
      toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,link,code",
      pagebreak_separator: "<p class='page-separator'>&nbsp;</p>",
      plugins: ["link", "code", "paste"],
      uploadimage_form_url: "/tinymce_assets",
      relative_urls: false,
      remove_script_host: false,
      oninit : "setPlainText"
    })
  });

app/views/admin/categories/index.slim
dl
  - @categories.each do |cat|
    dt = link_to cat.name, admin_category_path(cat)
    dd = cat.description

app/views/admin/categories/new.slim
.small-12.medium-8.columns.small-centered.medium-centered
  br
  br
  h1 Create New Category
  = form_for([:admin, @category]) do |f|
    .row
      .large-6.columns.small-12
        =f.label :name
        =f.text_field :name

    =f.label :description
    =f.text_area :description, rows: "8", class: "tinymce"

    =f.submit "Create Category"
br
br

javascript:
  $("document:ready", function() {
    $(".tinymce").tinymce({
      theme: "modern",
      toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,link,code",
      pagebreak_separator: "<p class='page-separator'>&nbsp;</p>",
      plugins: ["link", "code", "paste"],
      uploadimage_form_url: "/tinymce_assets",
      relative_urls: false,
      remove_script_host: false,
      oninit : "setPlainText"
    })
  });

app/views/admin/categories/show.slim
h1 = @category.name
hr
h2 Post in this Category

table
  thead
    tr
      th width="200" Title
      th Content
      th width="150" Action
  tbody
    - @category.posts.each do |post|
      tr
        td = post.title
        td = strip_tags(post.body).truncate(200)
        td = link_to "Edit", edit_admin_post_path(post)

app/views/admin/posts/edit.slim
.small-12.medium-8.columns.small-centered.medium-centered
  br
  br
  h1 Edit Post
  = link_to "Delete", admin_post_path(@post), method: :delete, class: "button right small alert"
  = form_for([:admin, @post], { multipart: true }) do |f|
    .row
      .large-6.columns.small-12
        =f.label :title
        =f.text_field :title

        =f.label :main_image
        =f.file_field :main_image

      .large-6.columns.small-12
        =f.label :category, "Category"
        =f.collection_select :category_id, @categories, :id, :name

    =f.label :body
    =f.text_area :body, rows: "8", class: "tinymce"

    =f.label :tags
    =f.text_field :tags

    br

    .row
      .large-7.columns.small-12
        = f.label :draft
          span= "Draft:  "
          = f.check_box :draft

        = f.label :featured
          span= "Featured:  "
          = f.check_box :featured

        = f.label :sidebar
          span= "Sidebar:  "
          = f.check_box :sidebar

      .large-5.columns.small-12
        =f.label :pub_date, "Publish Date"
        =f.date_field :pub_date




    = f.submit "Update Post", class: "button secondary small"

javascript:
  $("document:ready", function() {
    $(".tinymce").tinymce({
      theme: "modern",
      toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,link,code",
      pagebreak_separator: "<p class='page-separator'>&nbsp;</p>",
      plugins: ["link", "code", "paste"],
      uploadimage_form_url: "/tinymce_assets",
      relative_urls: false,
      remove_script_host: false,
      force_br_newlines: false,
      cleanup: false,
      apply_source_formatting: false,
      oninit : "setPlainText"
    })


  });

app/views/admin/posts/index.slim
h1 All Posts
hr
ul.large-block-grid-3.small-block-grid-1
  - @posts.each do |post|
    li
      .panel
        span.right
          = link_to "Edit", edit_admin_post_path(post)
        h3= link_to post.title, admin_post_path(post)
        p= post.pub_date
        p= strip_tags(post.body).truncate(150)
= paginate @posts

- if @featured_posts
  hr

  h1 Featured Posts
  hr
  ul.large-block-grid-3.small-block-grid-1
    - @featured_posts.each do |post|
      li
        .panel
          span.right
            = link_to "Edit", edit_admin_post_path(post)
          h3= link_to post.title, admin_post_path(post)
          p= post.pub_date
          p= strip_tags(post.body).truncate(150)
  = paginate @posts

  - if @sidebar_posts
    hr

    h1 Sidebar Posts
    hr
    ul.large-block-grid-3.small-block-grid-1
      - @featured_posts.each do |post|
        li
          .panel
            span.right
              = link_to "Edit", edit_admin_post_path(post)
            h3= link_to post.title, admin_post_path(post)
            p= post.pub_date
            p= strip_tags(post.body).truncate(150)
    = paginate @posts

app/views/admin/posts/new.slim
.small-12.medium-8.columns.small-centered.medium-centered
  br
  br
  h1 Create New Post
  = form_for([:admin, @post], :html => {:multipart => true} ) do |f|
    .row
      .large-6.columns.small-12
        =f.label :title
        =f.text_field :title

        =f.label :main_image
        =f.file_field :main_image

      .large-6.columns.small-12
        =f.label :category, "Category"
        =f.collection_select :category_id, @categories, :id, :name

    =f.label :body
    =f.text_area :body, rows: "8", class: "tinymce"

    =f.label :tags
    =f.text_field :tags

    br

    .row
      .large-7.columns.small-12
        = f.label :draft
          span= "Draft:  "
          = f.check_box :draft

        = f.label :featured
          span= "Featured:  "
          = f.check_box :featured

        = f.label :sidebar
          span= "Sidebar:  "
          = f.check_box :sidebar

      .large-5.columns.small-12
        =f.label :pub_date, "Publish Date"
        =f.date_field :pub_date

    =f.submit "Create Post"


javascript:
  $("document:ready", function() {
    $(".tinymce").tinymce({
      theme: "modern",
      toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,link,code",
      pagebreak_separator: "<p class='page-separator'>&nbsp;</p>",
      plugins: ["link", "code", "paste"],
      uploadimage_form_url: "/tinymce_assets",
      relative_urls: false,
      remove_script_host: false,
      oninit : "setPlainText"
    })
  });

app/views/admin/posts/show.slim
.small-12.columns
  h1 = @post.title
  - if current_user
    span.right
      = link_to "Edit", edit_admin_post_path(@post), class: "button small"

  h6 = "Status: " + @post.status
  h6 = "Published Date: " + @post.pub_date.to_s

  .row
    .large-6.columns.small-12
      - unless @post.main_image.nil?
        = image_tag @post.main_image.url :thumb

    .large-6.columns.small-12
      .panel
        h3 Tags:
        p = @post.tags

  p = simple_format(@post.body)

app/views/categories/show.html.erb
<div id="main-wrapper">
  <div id="main" class="container">
    <div class="row">
      <!-- Content -->
        <div id="content" class="12u 12u(mobile)">
          <h2><%= @category.name %></h2>
          <h5><%= simple_format(@category.description)%></h5>
        </div>

        <div id="content" class="8u 12u(mobile)">
          <!-- Post -->
          <% @category.posts.order(:created_at).each do |post| %>
            <article class="post box" style="box-shadow: none;">
              <header>
                <h2><a href="#"><%= post.title%></a></h2>
              </header>
              <a href="#" class="image featured"><%= image_tag post.main_image %></a>
              <h3><%= post.pub_date %></h3>
              <%= strip_tags(post.body).truncate(200) %>
              <ul class="actions">
                <li><%= link_to 'Continue Reading', public_show_path(post.slug) %></a></li>
              </ul>
            </article>
          <% end %>
        </div>
        <div id="sidebar" class="4u 12u(mobile)">
          <%= render 'static_pages/sidebar' %>
        </div>
          <% if @category.posts.nil? %>
            <br />
            <br />
            <hr />
            <h2>Posts Comming Soon!</h2>
          <% end %>
        <!-- Sidebar -->


    </div>
  </div>
</div>

app/views/layouts/_features.html.erb
<div id="features-wrapper">
  <section id="features" class="container">
    <header>
      <h2><strong>Featured Posts</strong></h2>
    </header>
    <div class="row">
      <% @featured_posts.each do |post|%>
        <div class="4u 12u(mobile)">
          <!-- Feature -->
            <section>
              <a href="#" class="image featured"><%= image_tag post.main_image.url :medium  %></a>
              <header>
                <h3><%= post.title %></h3>
              </header>
              <p><%= strip_tags(post.body).truncate(250) %></p>
            </section>
        </div>
      <% end %>
    </div>

app/views/layouts/_nav.slim
nav.top-bar data-topbar="" role="navigation"
  ul.title-area
    li.name
      h1
        a href="#" Admin
    /! Remove the class "menu-icon" to get rid of menu icon. Take out "Menu" to just have icon alone
    li.toggle-topbar.menu-icon
      a href="#"
        span Menu
  section.top-bar-section
    /! Right Nav Section
    ul.right
      li.active
        a href="/admin/posts"  View All Posts
      li.has-dropdown
        a href="#"  Admin Dropdown
        ul.dropdown
          li
            a href="/admin/posts/new"  Create New Post
          li
            a href="/admin/categories/new" Create New Categories
          li
            a href="/admin/posts"  Manage Existing Posts
          li
            a href="/admin/categories" Manage Existing categories
    /! Left Nav Section
    ul.left
      li.has-form
        .row.collapse
          .large-8.small-9.columns
            input placeholder=("Pending Development") type="text" /
          .large-4.small-3.columns
            a.alert.button.expand href="#"  Search

app/views/layouts/_public_footer.html.erb
<div id="footer-wrapper">
  <div id="footer" class="container">
    <header>
      <h2>Questions or comments? <strong>Get in touch:</strong></h2>
    </header>
    <div class="row">
      <div class="6u 12u(mobile)">
        <section>
          <form method="post" action="MAILTO:halleson.white@gmail.com" enctype="text/plain">
            <div class="row 50%">
              <div class="6u 12u(mobile)">
                <input name="name" placeholder="Name" type="text" />
              </div>
              <div class="6u 12u(mobile)">
                <input name="email" placeholder="Email" type="text" />
              </div>
            </div>
            <div class="row 50%">
              <div class="12u">
                <textarea name="message" placeholder="Message"></textarea>
              </div>
            </div>
            <div class="row 50%">
              <div class="12u">
                <input type="submit" value="Send">
                <input type="reset" value="Reset">
              </div>
            </div>
          </form>
        </section>
      </div>
      <div class="6u 12u(mobile)">
        <section>
          <p>Welcome! I hope this is a place you love and want to visit everyday. We are new so feedback is crucial! Please, send us your thoughts and make sure to follow us and like us on social media. Stay golden!</p>
          <div class="row">
            <div class="6u 12u(mobile)">
              <ul class="icons">
                <li class="icon fa-home">
                  Lawrenceville, GA  30044<br />
                  USA
                </li>
                <li class="icon fa-envelope">
                  <a href="#">halleson.white@gmail.com</a>
                </li>
              </ul>
            </div>
            <div class="6u 12u(mobile)">
              <ul class="icons">
                <li class="icon fa-twitter">
                  <a href="https://twitter.com/ThreePeas_Blog">@ThreePeas_Blog</a>
                </li>
                <li class="icon fa-instagram">
                  <a href="https://instagram.com/hallesonthompson/">@hallesonthompson</a>
                </li>
                <li class="icon fa-facebook">
                  <a href="https://www.facebook.com/pages/Three-Peas-in-a-Pod-Blog/711108075682264">Follow</a>
                </li>
              </ul>
            </div>
          </div>
        </section>
      </div>
    </div>
  </div>
  <div id="copyright" class="container">
    <ul class="links">
      <li>The End</li>
    </ul>
  </div>
</div>

app/views/layouts/_public_header.html.erb
<div id="header-wrapper">
  <div id="header" class="container">

    <!-- Logo -->
      <h1 id="logo"><a href="index.html">Three Peas in a Pod</a></h1>
      <p>An honest and open space.</p>

    <!-- Nav -->
      <nav id="nav">
        <ul>
          <li><a class="icon fa-home" href="/"><span>Home</span></a></li>
          <li>
            <a href="#" class="icon fa-sitemap"><span>Pigeonoles &amp; Pockets</span></a>
            <ul>
              <% Category.all.each do |cat| %>
                <li><%= link_to cat.name, "/categories/#{cat.slug}" %></li>
              <% end %>
            </ul>
          </li>
          <li><a class="icon fa-facebook" href="https://www.facebook.com/pages/Three-Peas-in-a-Pod-Blog/711108075682264"><span>Facebook</span></a></li>
          <li><a class="icon fa-twitter" href="https://twitter.com/ThreePeas_Blog"><span>Twitter</span></a></li>
        </ul>
      </nav>

  </div>
</div>

app/views/layouts/application.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta content="width=device-width, initial-scale=1.0" name="viewport"
    title
      =content_for?(:title) ? yield(:title) : "Admin Portal"
    = stylesheet_link_tag    "application"
    = javascript_include_tag "vendor/modernizr"
    = javascript_include_tag "application"
    <script src="//use.typekit.net/gif6roa.js"></script>
    <script>try{Typekit.load();}catch(e){}</script>
    = csrf_meta_tags
  body
    = render 'layouts/nav' if current_user
    p.notice
      = notice
    p.alert
      = alert
    .row
      .small-12.columns.small-centered
        = yield

app/views/layouts/public.html.erb
<!DOCTYPE HTML>
<!--
	Strongly Typed by HTML5 UP
	html5up.net | @n33co
	Free for personal and commercial use under the CCA 3.0 license (html5up.net/license)
-->
<html>
	<head>
		<title><%= content_for?(:title) ? content_for(:title) : 'Three Peas in a Pod' %></title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1" />
		<!--[if lte IE 8]><script src="assets/css/ie/html5shiv.js"></script><![endif]-->
    <%= stylesheet_link_tag("public") %>
		<!-- <%= stylesheet_link_tag("font-awesome.min.scss") %> -->

		<!-- <link rel="stylesheet" href="assets/font-awesome.min.scss" /> -->
		<!--[if lte IE 8]><script src="assets/css/ie/respond.min.js"></script><![endif]-->
		<!-- Scripts -->
		<%= javascript_include_tag "jquery-1.11.3.min.js" %>
		<%= javascript_include_tag "swag.js"%>
		<%= javascript_include_tag "jquery.dropotron.min.js" %>
		<%= javascript_include_tag "skel.min.js" %>
		<%= javascript_include_tag "skel-viewport.min.js" %>
		<%= javascript_include_tag "util.js" %>
		<%= javascript_include_tag "main.js" %>

	</head>
	<body class="homepage">
		<div id="page-wrapper">
			<%= render 'layouts/public_header'%>
			<%= yield %>
			<%= render 'layouts/public_footer'%>
		</div>
	</body>
</html>

app/views/posts/edit.slim
.small-12.medium-8.columns.small-centered.medium-centered
  br
  br
  h1 Edit Post
  = link_to "Delete", post_path(@post), method: :delete, class: "button right small alert"
  = form_for(@post, { multipart: true }) do |f|
    .row
      .large-6.columns.small-12
        =f.label :title
        =f.text_field :title

        =f.label :main_image
        =f.file_field :main_image

    =f.label :body
    =f.text_area :body, rows: "8", class: "tinymce"

    =f.label :tags
    =f.text_field :tags

    br

    .row
      .large-7.columns.small-12
        = f.label :draft
          span= "Draft:  "
          = f.check_box :draft

        = f.label :featured
          span= "Featured:  "
          = f.check_box :featured

        = f.label :sidebar
          span= "Sidebar:  "
          = f.check_box :sidebar
          
      .large-5.columns.small-12
        =f.label :pub_date, "Publish Date"
        =f.date_field :pub_date




    = f.submit "Update Post", class: "button secondary small"

javascript:
  $("document:ready", function() {
    $(".tinymce").tinymce({
      theme: "modern",
      toolbar: "bold,italic,underline,|,bullist,numlist,outdent,indent,|,undo,redo,|,pastetext,pasteword,selectall,|,uploadimage,link,code",
      pagebreak_separator: "<p class='page-separator'>&nbsp;</p>",
      plugins: ["uploadimage", "link", "code"],
      uploadimage_form_url: "/tinymce_assets",
      relative_urls: false,
      remove_script_host: false
    })
  });

app/views/posts/index.slim
h1 All Posts
hr
ul.large-block-grid-3.small-block-grid-1
  - @posts.each do |post|
    li
      .panel
        span.right
          = link_to "Edit", edit_post_path(post)
        h3= link_to post.title, post_path(post)
        p= post.pub_date
        p= strip_tags(post.body).truncate(150)
= paginate @posts

- if @featured_posts
  hr

  h1 Featured Posts
  hr
  ul.large-block-grid-3.small-block-grid-1
    - @featured_posts.each do |post|
      li
        .panel
          span.right
            = link_to "Edit", edit_post_path(post)
          h3= link_to post.title, post_path(post)
          p= post.pub_date
          p= strip_tags(post.body).truncate(150)
  = paginate @posts

  - if @sidebar_posts
    hr

    h1 Sidebar Posts
    hr
    ul.large-block-grid-3.small-block-grid-1
      - @featured_posts.each do |post|
        li
          .panel
            span.right
              = link_to "Edit", edit_post_path(post)
            h3= link_to post.title, post_path(post)
            p= post.pub_date
            p= strip_tags(post.body).truncate(150)
    = paginate @posts

app/views/posts/show.slim
.small-12.columns
  h1 = @post.title
  - if current_user
    span.right
      = link_to "Edit", edit_post_path(@post), class: "button small"

  h6 = "Status: " + @post.status
  h6 = "Published Date: " + @post.pub_date.to_s

  .row
    .large-6.columns.small-12
      - unless @post.main_image.nil?
        = image_tag @post.main_image.url :thumb

    .large-6.columns.small-12
      .panel
        h3 Tags:
        p = @post.tags

  p = simple_format(@post.body)

app/views/static_pages/_features.html.erb
<div id="features-wrapper">
  <section id="features" class="container">
    <header>
      <h2><strong>Featured Posts</strong></h2>
    </header>
    <div class="row">
      <% @featured_posts.each do |post|%>
        <div class="4u 12u(mobile)">
          <!-- Feature -->
            <section>
              <%= link_to public_show_path(post.slug), class: "image featured" do %>
                <%= image_tag post.main_image.url :medium  %>
              <% end %>
              <header>
                <h3><%= post.title %></h3>
              </header>
              <p><%= strip_tags(post.body).truncate(250) %></p>
            </section>
        </div>
      <% end %>
    </div>

app/views/static_pages/_sidebar.html.erb
<% @sidebar_posts.each do |post| %>
  <section>
    <ul class="divided">
        <li>
            <article class="box excerpt">
              <header>
                <span class="date"><%= post.pub_date %></span>
                <h3><%= link_to post.title, public_show_path(post.slug) %></h3>
              </header>
              <p><%= strip_tags(post.body).truncate(200) %></p>
            </article>
        </li>
    </ul>
  </section>
<% end %>